services:
    php-sda:
        image: supplier-data-aggregator-php:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
        environment:
            APP_ENV: ${APP_ENV}
        networks:
          - internal_sync_network
#        For prod
#        command: composer run-script serve

networks:
  internal_sync_network:
    driver: bridge
    external: true
    name: internal_sync_network