services:
    php-sda:
        image: supplier-data-aggregator-php:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
        environment:
            APP_ENV: ${APP_ENV}
        container_name: php-sda

#        For prod
#        command: composer run-script serve

# For prod
#networks:
#    walmart_scraper_network:
#        external: true
#        name: walmart_scraper_network